name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
        COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
      run: |
        pytest MyFunctions/tests

    - name: Log in to Azure
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure
      env:
        AZURE_FUNCTIONAPP_NAME: hammadresume-funcAPI
        AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        az functionapp deployment source config-zip \
          --resource-group Class-Hammad-Kamran-RG \
          --name $AZURE_FUNCTIONAPP_NAME \
          --src $AZURE_FUNCTIONAPP_PACKAGE_PATH

