name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run tests
        env:
          PYTHONPATH: MyFunction  # Add MyFunction to the Python path
        run: |
          # Run your tests here
          pytest MyFunction/tests  # Run pytest pointing to the correct test directory

      - name: Deploy to Azure
        env:
          AZURE_FUNCTIONAPP_NAME: hammadresume-funcAPI
          AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az functionapp deployment source config-zip \
            --resource-group Class-Hammad-Kamran-RG \
            --name $AZURE_FUNCTIONAPP_NAME \
            --src $AZURE_FUNCTIONAPP_PACKAGE_PATH
